# Generated by Django 6.1.1 on 2026-09-25 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категорія робіт')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис категорії')),
            ],
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва роботи (підкатегорія)')),
                ('description', models.TextField(verbose_name='Детальний опис роботи')),
                ('price', models.CharField(max_length=100, verbose_name='Орієнтовна ціна')),
                ('image', models.ImageField(blank=True, null=True, upload_to='works_photos/', verbose_name='Фото роботи')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoran.category', verbose_name='Категорія')),
            ],
        ),
    ]
